services:
  dyma-postgresql:
    image: postgres:17
    container_name: dyma-postgres-production
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5ML^Es#x%4U&DK6c
    ports:
      - '5424:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data