services:
  dyma-postgresql:
    image: postgres:17
    container_name: dyma-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - dyma-postgres-data:/var/lib/postgresql/data

volumes:
  dyma-postgres-data:
